project:
  type: website
  output-dir: docs

website:
  title: "Prasanga Paudel's Data Analysis Portfolio"
  navbar:
    left:
      - text: "About Me"
        file: aboutme.qmd
      - text: "Projects"
        menu:
          - text: "Presentation Exercise"
            file: presentation-exercise/presentation-exercise.qmd
          - text: "Model Fitting Exercise"
            file: fitting-exercise/fitting-exercise.qmd
          - text: "Machine Learning"
            file: ml-models-exercise/ml-models-exercise.qmd
          - text: "Tidy Tuesday Exercise"
            file: tidytuesday-exercise/tidytuesday-exercise.qmd
          - text: "Shopping Behavior"
            file: metrics-exercise/metrics.qmd
          - text: "Milk Elasticity"
            file: pricetheory-exercise/pricetheory.qmd
    right:
      - icon: github
        href: https://github.com/xprasanga/prasangapaudel-portfolio

format:
  html:
    theme: darkly
    highlight: zenburn
    css: styles.css
    toc: false