project: 
  type: website
  output-dir: docs

website:
  title: "Prasanga Paudel's Data Analysis Portfolio"
  navbar:
    left:
      - text: "Prasanga Paudel's MADA Portfolio"
        file: aboutme.qmd
      - text: "Projects"
        menu:
          - text: "Starter Analysis Exercise"
            file: starter-analysis-exercise/products/report/starter-analysis-report.qmd
          - text: "R Coding Exercise"
            file: coding-exercise/coding-exercise.qmd
    right:
      - icon: github 
        href: https://github.com/xprasanga/prasangapaudel-MADA-portfolio       
format:
  html:
    theme: cosmo
    highlight: zenburn
    css: styles.css
    toc: FALSE
